version: '3.9'
services:
  frontend:
    build: ./frontend
    container_name: app-frontend
    ports:
      - 3000:3000
    platform: linux/x86_64
    working_dir: /app-frontend
    depends_on:
      backend:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "lsof", "-t", "-i:3000"]
      timeout: 10s
      retries: 5
  backend:
    container_name: app-backend
    build: ./backend
    ports:
      - 3001:3001
    platform: linux/x86_64
    working_dir: /app-backend
    volumes: 
      - ./backend/src:/app-backend/src
    environment:
      - MYSQLDATABASE=railway
      - MYSQLHOST=containers-us-west-102.railway.app
      - MYSQLPASSWORD=3JQAtTBiy2oO4Gxo1qvz
      - MYSQLPORT=8040
      - MYSQLUSER=root
      - MYSQL_URL=mysql://${{ MYSQLUSER }}:${{ MYSQLPASSWORD }}@${{ MYSQLHOST }}:${{ MYSQLPORT }}/${{ MYSQLDATABASE }}
    healthcheck:
      test: ["CMD", "lsof", "-t", "-i:3001"]
      timeout: 10s
      retries: 5
  # db:
  #   image: mysql:8.0.21
  #   container_name: db
  #   platform: linux/x86_64
  #   ports:
  #     - 3002:3306
  #   environment:
  #     - MYSQL_ROOT_PASSWORD=123456
  #   restart: 'always'
  #   healthcheck:
  #     test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
  #     timeout: 10s
  #     retries: 5
  #   cap_add:
  #     - SYS_NICE